name: My First Workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List Repository Files
        run: ls -ltra

      - name: Run Script
        run: |
          chmod +X ./ascii-script.sh
           ./ascii-script.sh
